Blog/Controllers/AuthController.cs
using Blog.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    public class AuthController : Controller
    {
        private SignInManager<IdentityUser> _signInManager;
        public AuthController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            var result = await _signInManager.PasswordSignInAsync(vm.UserName, vm.Password, false, false);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog/Controllers/PanelController.cs
using Blog.Data.FileManager;
using Blog.Data.Repository;
using Blog.Models;
using Blog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;
        public PanelController(IRepository repo, IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }

        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                var post = _repo.GetPost(id.Value);
                var postVM = new PostViewModel
                {
                    Id = post.Id,
                    Title = post.Title,
                    Body = post.Body,
                    CurrentImage = post.Image,
                    Description = post.Description,
                    Category = post.Category,
                    Tags = post.Tags
                };
                return View(postVM);
            }

            return View(new PostViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel postVM)
        {
            var post = new Post
            {
                Id = postVM.Id,
                Title = postVM.Title,
                Body = postVM.Body,
                Description = postVM.Description,
                Category = postVM.Category,
                Tags = postVM.Tags
            };

            if(postVM.Image == null)
            {
                post.Image = postVM.CurrentImage;
            } else
            {
                if (!string.IsNullOrEmpty(postVM.CurrentImage))
                {
                    _fileManager.RemoveImage(postVM.CurrentImage);
                }
                post.Image = await _fileManager.SaveImageAsync(postVM.Image);
            }

            if (post.Id > 0)
            {
                _repo.UpdatePost(post);
            }
            else
            {
                _repo.AddPost(post);
            }

            if (await _repo.SaveChangesAsync())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(post);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            var post = _repo.GetPost(id);

            if (!string.IsNullOrEmpty(post.Image))
            {
                _fileManager.RemoveImage(post.Image);
            }

            _repo.RemovePost(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.Keywords" />

    <environment include="Production">
        <link href="~/css/site.min.css" rel="stylesheet" />
    </environment>
    <environment include="Development">
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>

</head>
<body>
    <div>
        <nav>
            <a asp-controller="Home" asp-action="Index">Home</a>
            <a asp-controller="Home" asp-action="Index" asp-route-category="Programming">Programming</a>
            <a asp-controller="Home" asp-action="Index" asp-route-category="Travel">Travel</a>
            <a asp-controller="Home" asp-action="Index" asp-route-category="Photography">Photography</a>
            <a asp-controller="Panel" asp-action="Index">Admin Panel</a>

            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Panel" asp-action="Edit">Create Post</a>
                <a asp-controller="Auth" asp-action="Logout">Logout</a>
            }
            else
            {
                <a asp-controller="Auth" asp-action="Login">Sign In</a>
            }
        </nav>
    </div>
    
    <div>
        @RenderBody()
    </div>

    @RenderSection("scripts", false)
</body>
</html>